# Chapter 3: Moving from pandas to Polars

In [1]:
import polars as pl
pl.__version__  # The book is built with Polars version 1.20.0

'1.33.0'

## Animals

In [2]:
! cat data/animals.csv

animal,class,habitat,diet,lifespan,status,features,weight
dolphin,mammal,oceans/rivers,carnivore,40,least concern,high intelligence,150
duck,bird,wetlands,omnivore,8,least concern,waterproof feathers,3
elephant,mammal,savannah,herbivore,60,endangered,large ears and trunk,8000
ibis,bird,wetlands,omnivore,16,least concern,"long, curved bill",1
impala,mammal,savannah,herbivore,12,least concern,"long, curved horns",70
kudu,mammal,savannah,herbivore,15,least concern,spiral horns,250
narwhal,mammal,arctic ocean,carnivore,40,near threatened,"long, spiral tusk",
panda,mammal,forests,herbivore,20,vulnerable,black and white coloration,100
polar bear,mammal,arctic,carnivore,25,vulnerable,thick fur and blubber,720
ray,fish,oceans,carnivore,20,"","flat, disc-shaped body",90

## Similarities to Recognize

## Appearances to Appreciate

In [3]:
import pandas as pd
import polars as pl

### Differences in Code

In [4]:
animals_pd = pd.read_csv("data/animals.csv", sep=",", header=0)
animals_pl = pl.read_csv("data/animals.csv", separator=",", has_header=True)

print(f"{type(animals_pd) = }")
print(f"{type(animals_pl) = }")

type(animals_pd) = <class 'pandas.DataFrame'>
type(animals_pl) = <class 'polars.dataframe.frame.DataFrame'>

### Differences in Display

In [5]:
animals_pd

,animal,class,habitat,diet,lifespan,status,features,weight
0,dolphin,mammal,oceans/rivers,carnivore,40,least concern,high intelligence,150.0
1,duck,bird,wetlands,omnivore,8,least concern,waterproof feathers,3.0
2,elephant,mammal,savannah,herbivore,60,endangered,large ears and trunk,8000.0
3,ibis,bird,wetlands,omnivore,16,least concern,"long, curved bill",1.0
4,impala,mammal,savannah,herbivore,12,least concern,"long, curved horns",70.0
5,kudu,mammal,savannah,herbivore,15,least concern,spiral horns,250.0
6,narwhal,mammal,arctic ocean,carnivore,40,near threatened,"long, spiral tusk",NaN
7,panda,mammal,forests,herbivore,20,vulnerable,black and white coloration,100.0
8,polar bear,mammal,arctic,carnivore,25,vulnerable,thick fur and blubber,720.0
9,ray,fish,oceans,carnivore,20,NaN,"flat, disc-shaped body",90.0

In [6]:
animals_pl

shape: (10, 8)
┌────────────┬────────┬──────────────┬───────────┬──────────┬──────────────┬──────────────┬────────┐
│ animal     ┆ class  ┆ habitat      ┆ diet      ┆ lifespan ┆ status       ┆ features     ┆ weight │
│ ---        ┆ ---    ┆ ---          ┆ ---       ┆ ---      ┆ ---          ┆ ---          ┆ ---    │
│ str        ┆ str    ┆ str          ┆ str       ┆ i64      ┆ str          ┆ str          ┆ i64    │
╞════════════╪════════╪══════════════╪═══════════╪══════════╪══════════════╪══════════════╪════════╡
│ dolphin    ┆ mammal ┆ oceans/river ┆ carnivore ┆ 40       ┆ least        ┆ high         ┆ 150    │
│            ┆        ┆ s            ┆           ┆          ┆ concern      ┆ intelligence ┆        │
│ duck       ┆ bird   ┆ wetlands     ┆ omnivore  ┆ 8        ┆ least        ┆ waterproof   ┆ 3      │
│            ┆        ┆              ┆           ┆          ┆ concern      ┆ feathers     ┆        │
│ elephant   ┆ mammal ┆ savannah     ┆ herbivore ┆ 60       ┆ endangered   ┆ large ears   ┆ 8000   │
│            ┆        ┆              ┆           ┆          ┆              ┆ and trunk    ┆        │
│ ibis       ┆ bird   ┆ wetlands     ┆ omnivore  ┆ 16       ┆ least        ┆ long, curved ┆ 1      │
│            ┆        ┆              ┆           ┆          ┆ concern      ┆ bill         ┆        │
│ impala     ┆ mammal ┆ savannah     ┆ herbivore ┆ 12       ┆ least        ┆ long, curved ┆ 70     │
│            ┆        ┆              ┆           ┆          ┆ concern      ┆ horns        ┆        │
│ kudu       ┆ mammal ┆ savannah     ┆ herbivore ┆ 15       ┆ least        ┆ spiral horns ┆ 250    │
│            ┆        ┆              ┆           ┆          ┆ concern      ┆              ┆        │
│ narwhal    ┆ mammal ┆ arctic ocean ┆ carnivore ┆ 40       ┆ near         ┆ long, spiral ┆ null   │
│            ┆        ┆              ┆           ┆          ┆ threatened   ┆ tusk         ┆        │
│ panda      ┆ mammal ┆ forests      ┆ herbivore ┆ 20       ┆ vulnerable   ┆ black and    ┆ 100    │
│            ┆        ┆              ┆           ┆          ┆              ┆ white        ┆        │
│            ┆        ┆              ┆           ┆          ┆              ┆ coloration   ┆        │
│ polar bear ┆ mammal ┆ arctic       ┆ carnivore ┆ 25       ┆ vulnerable   ┆ thick fur    ┆ 720    │
│            ┆        ┆              ┆           ┆          ┆              ┆ and blubber  ┆        │
│ ray        ┆ fish   ┆ oceans       ┆ carnivore ┆ 20       ┆              ┆ flat,        ┆ 90     │
│            ┆        ┆              ┆           ┆          ┆              ┆ disc-shaped  ┆        │
│            ┆        ┆              ┆           ┆          ┆              ┆ body         ┆        │
└────────────┴────────┴──────────────┴───────────┴──────────┴──────────────┴──────────────┴────────┘

In [ ]:
animals_pd["animal"]

In [ ]:
animals_pl.get_column("animal")

In [ ]:
animals_pd = animals_pd.drop(columns=["habitat", "diet", "features"])
animals_pd

In [ ]:
animals_pl = animals_pl.drop("habitat", "diet", "features")
animals_pl

## Concepts to Unlearn

### Index

In [ ]:
animals_pd.index

In [ ]:
animals_agg_pd = animals_pd.groupby(["class", "status"])[["weight"]].mean()
animals_agg_pd

In [ ]:
animals_agg_pd.index

In [ ]:
animals_agg_pd.reset_index()

In [ ]:
animals_pl.group_by(["class", "status"]).agg(pl.col("weight").mean())

### Axes

In [ ]:
# This raises a KeyError:
# animals_pd.drop("weight")

In [ ]:
animals_pd.drop("weight", axis=1)

### Indexing and Slicing

In [ ]:
animals_pd[["animal", "class"]]

In [ ]:
animals_pd[animals_pd["status"] == "endangered"]

In [ ]:
animals_pd[:3]

In [ ]:
animals_pd["weight"] = animals_pd["weight"] * 1000

In [ ]:
animals_pd["weight"]

In [ ]:
animals_pd["weight"] = animals_pd["weight"].sort_values()

In [ ]:
animals_pd["weight"]

### Eagerness

In [ ]:
lazy_query = (
    pl.scan_csv("data/animals.csv")
    .group_by("class")
    .agg(pl.col("weight").mean())
    .filter(pl.col("class") == "mammal")
)

In [ ]:
lazy_query.show_graph(optimized=False)

In [ ]:
lazy_query.show_graph()

In [ ]:
lazy_query.collect()

### Relaxedness

## Syntax to Forget

### Common Operations Side By Side

#### Removing duplicate values

In [ ]:
animals_pd.drop_duplicates(subset="class")

In [ ]:
animals_pl.unique(subset="class")

#### Removing missing values

In [ ]:
animals_pd.dropna(subset="weight")

In [ ]:
animals_pl.drop_nulls(subset="weight")

#### Sorting rows

In [ ]:
animals_pd.sort_values("weight", ascending=False)

In [ ]:
animals_pl.sort("weight", descending=True)

#### Casting an existing column

In [ ]:
animals_pd.assign(lifespan=animals_pd["lifespan"].astype(float))

In [ ]:
animals_pl.with_columns(pl.col("lifespan").cast(pl.Float64))

#### Aggregating rows

In [ ]:
animals_pd.groupby(["class", "status"])[["weight"]].mean()

In [ ]:
animals_pl.group_by("class", "status").agg(pl.col("weight").mean())

## To and From pandas

In [ ]:
animals_pl = pl.DataFrame(animals_pd)

animals_pl

In [ ]:
there_and_back_again_df = animals_pl.to_pandas()

there_and_back_again_df

## Takeaways